### ISSUE TITLE
Use IPFS' DNSLink for carbon.fyi

### ISSUE THREAD

**Issue by danimesq** [Offsetra/ethereum-emissions-calculator#2]

**Comment by danimesq** [comment]
@brendanmc6 @de-souza

**Comment by brendanmc6** [comment]
Any advice on the best way to do this? Or what the benefits are? I've never used IPFS.

**Comment by danimesq** [comment]
@brendanmc6
> Or what the benefits are? I've never used IPFS.

It will permit carbon.fyi to be redirected into an immutable, always available version if IPFS Companion is installed or Brave browser used.
Most of the Ethereans uses and/or support IPFS.

> Any advice on the best way to do this?

Use an service such as pinata.cloud to upload your site, then copy the hash/CID, and then: https://docs.ipfs.io/concepts/dnslink/

**Comment by brendanmc6** [comment]
Thank you, we are working on this for carbon.fyi and have a working prototype-- but this package should only be concerned with the emissions-calculator package itself :)
