### ISSUE TITLE
inaccurate calculations

### ISSUE THREAD

**Issue by DurinDwarf** [Offsetra/ethereum-emissions-calculator#4]
Tested with 3 of my Ethereum addresses.
Doesn't find the actual number of ERC tokens held , so a wrong result

**Comment by brendanmc6** [comment]
@DurinDwarf are you willing to send me your address for testing? Or maybe you can find me another public address to test with. I am not able to reproduce this issue...

It should accurately count the gas spent for ERC20 or ERC721 transactions *sent* from your address

**Comment by brendanmc6** [comment]
Closing as I can't reproduce with the given information.
